---

- hosts: laravel

  tasks:
    - name: Migrating DB
      shell: chdir={{ ansistrano_deploy_to }}/{{ ansistrano_current_dir }}
        {{ php_path }} artisan migrate --force
      register: migrate_result
      changed_when: "migrate_result.stdout != 'Nothing to migrate.'"
